language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb 
  - sudo dpkg -i hugo_0.48_Linux-64bit.deb
script:
  - hugo
  - npm install -g serverless@1.30.1
  - sls deploy -v -s ${TRAVIS_BRANCH}
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: "madepsilon.com"
  skip_cleanup: true
  local_dir: public
